services:
  app:
    build: .
    container_name: peerislands-ecommerce
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres 
    depends_on:
      - postgres-db
    restart: on-failure

  postgres-db:
    image: postgres:15-alpine
    container_name: ecommerce-postgres
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: